# -*- encoding: utf-8 -*-

=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "payjpv2/version"

Gem::Specification.new do |s|
  s.name        = "payjpv2"
  s.version     = PAYJPv2::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["PAY.JP"]
  s.email       = ["support@pay.jp"]
  s.homepage    = "https://github.com/payjp/payjpv2-ruby"
  s.summary     = "A Ruby client library for the PAY.JP v2 API"
  s.description = "A Ruby client library for the PAY.JP v2 API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.2"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
