=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::BalancesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BalancesApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::BalancesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BalancesApi' do
    it 'should create an instance of BalancesApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::BalancesApi)
    end
  end

  # unit tests for create_balance_url
  # Create Balance Url
  # @param balance_id 
  # @param [Hash] opts the optional parameters
  # @return [BalanceURLResponse]
  describe 'create_balance_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_balances
  # Get All Balances
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :since 指定した日付以降のデータを取得
  # @option opts [Time] :_until 指定した日付以前のデータを取得
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @option opts [BalanceState] :state stateが指定した値であるオブジェクトに限定
  # @option opts [Boolean] :closed closedが指定した値であるオブジェクトに限定
  # @option opts [Time] :since_due_date 入金予定日/振込期限日が指定した日時以降のデータのみ取得
  # @option opts [Time] :until_due_date 入金予定日/振込期限日が指定した日時以前のデータのみ取得
  # @return [BalanceListResponse]
  describe 'get_all_balances test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_balance
  # Retrieve Balance
  # @param balance_id 
  # @param [Hash] opts the optional parameters
  # @return [BalanceResponse]
  describe 'retrieve_balance test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
