=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::CheckoutSessionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutSessionsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::CheckoutSessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutSessionsApi' do
    it 'should create an instance of CheckoutSessionsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::CheckoutSessionsApi)
    end
  end

  # unit tests for create_checkout_session
  # Create Checkout Session
  # @param checkout_session_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionDetailsResponse]
  describe 'create_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.create_checkout_session(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.create_checkout_session(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_checkout_session_line_items
  # Get All Checkout Session Line Items
  # @param checkout_session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [CheckoutSessionLineItemListResponse]
  describe 'get_all_checkout_session_line_items test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_checkout_session_line_items(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_checkout_session_line_items(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_checkout_sessions
  # Get All Checkout Sessions
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [CheckoutSessionListResponse]
  describe 'get_all_checkout_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_checkout_sessions()
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_checkout_sessions(include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_checkout_session
  # Get Checkout Session
  # @param checkout_session_id 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionDetailsResponse]
  describe 'get_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_checkout_session(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_checkout_session(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for update_checkout_session
  # Update Checkout Session
  # @param checkout_session_id 
  # @param checkout_session_update_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionDetailsResponse]
  describe 'update_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.update_checkout_session(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.update_checkout_session(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

end
