=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::CheckoutSessionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutSessionsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::CheckoutSessionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutSessionsApi' do
    it 'should create an instance of CheckoutSessionsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::CheckoutSessionsApi)
    end
  end

  # unit tests for create_checkout_session
  # Create Checkout Session
  # @param checkout_session_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionDetailsResponse]
  describe 'create_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_checkout_sessions
  # Get All Checkout Sessions
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [CheckoutSessionListResponse]
  describe 'get_all_checkout_sessions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_checkout_session
  # Get Checkout Session
  # @param checkout_session_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :expand レスポンス返却時に展開したいオブジェクト名。指定したオブジェクトを同時に取得し、レスポンスに乗せて返却します。
  # @return [CheckoutSessionDetailsResponse]
  describe 'get_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_checkout_session
  # Update Checkout Session
  # @param checkout_session_id 
  # @param checkout_session_update_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionDetailsResponse]
  describe 'update_checkout_session test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
