=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::CustomersApi)
    end
  end

  # unit tests for create_customer
  # Create Customer
  # @param customer_create_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'create_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.create_customer(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.create_customer(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for delete_customer
  # Delete Customer
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'delete_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.delete_customer(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.delete_customer(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_customers
  # Get All Customers
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [CustomerListResponse]
  describe 'get_all_customers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_customers()
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_customers(include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_customer
  # Get Customer
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'get_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_customer(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_customer(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_customer_payment_methods
  # Get Customer Payment Methods
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [PaymentMethodListResponse]
  describe 'get_customer_payment_methods test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_customer_payment_methods(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_customer_payment_methods(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for update_customer
  # Update Customer
  # @param customer_id 
  # @param customer_update_request 
  # @param [Hash] opts the optional parameters
  # @return [CustomerResponse]
  describe 'update_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.update_customer(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.update_customer(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

end
