=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::EventsApi)
    end
  end

  # unit tests for get_all_events
  # Get All Events
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :since 指定した日付以降のデータを取得
  # @option opts [Time] :_until 指定した日付以前のデータを取得
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @option opts [String] :resource_id 取得するeventに紐づくAPIリソースのID (e.g. customer.id)
  # @option opts [String] :object 取得するeventに紐づくAPIリソースのobject。値はリソース名(e.g. customer, payment_intent)
  # @option opts [String] :type 取得するeventのtype
  # @return [EventListResponse]
  describe 'get_all_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_event
  # Get Event
  # @param event_id 
  # @param [Hash] opts the optional parameters
  # @return [EventResponse]
  describe 'get_event test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
