=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PaymentMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentMethodsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PaymentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'should create an instance of PaymentMethodsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PaymentMethodsApi)
    end
  end

  # unit tests for create_payment_method
  # Create Payment Method
  # @param payment_method_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'create_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_payment_methods
  # Get All Payment Methods
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [PaymentMethodListResponse]
  describe 'get_all_payment_methods test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_payment_method
  # Get Payment Method
  # @param payment_method_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'get_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_payment_method
  # Update Payment Method
  # @param payment_method_id 
  # @param payment_method_card_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'update_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
