=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PaymentMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentMethodsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PaymentMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentMethodsApi' do
    it 'should create an instance of PaymentMethodsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PaymentMethodsApi)
    end
  end

  # unit tests for attach_payment_method
  # Attach Payment Method
  # @param payment_method_id 
  # @param payment_method_attach_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'attach_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.attach_payment_method(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.attach_payment_method(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for create_payment_method
  # Create Payment Method
  # **このエンドポイントはテストモードでのみ使用できます。**
  # @param payment_method_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'create_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.create_payment_method(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.create_payment_method(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for detach_payment_method
  # Detach Payment Method
  # @param payment_method_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'detach_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.detach_payment_method(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.detach_payment_method(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_payment_methods
  # Get All Payment Methods
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [PaymentMethodListResponse]
  describe 'get_all_payment_methods test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_payment_methods()
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_payment_methods(include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_payment_method
  # Get Payment Method
  # @param payment_method_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'get_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_payment_method(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_payment_method(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_payment_method_by_card
  # Get Payment Method By Card
  # @param card_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'get_payment_method_by_card test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_payment_method_by_card(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_payment_method_by_card(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for update_payment_method
  # Update Payment Method
  # @param payment_method_id 
  # @param payment_method_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentMethodResponse]
  describe 'update_payment_method test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.update_payment_method(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.update_payment_method(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

end
