=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PaymentFlowsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentFlowsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PaymentFlowsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentFlowsApi' do
    it 'should create an instance of PaymentFlowsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PaymentFlowsApi)
    end
  end

  # unit tests for cancel_payment_flow
  # Cancel Payment Flow
  # @param payment_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentFlowCancelRequest] :payment_flow_cancel_request 
  # @return [PaymentFlowResponse]
  describe 'cancel_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.cancel_payment_flow(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.cancel_payment_flow(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for capture_payment_flow
  # Capture Payment Flow
  # @param payment_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentFlowCaptureRequest] :payment_flow_capture_request 
  # @return [PaymentFlowResponse]
  describe 'capture_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.capture_payment_flow(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.capture_payment_flow(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for confirm_payment_flow
  # Confirm Payment Flow
  # @param payment_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentFlowConfirmRequest] :payment_flow_confirm_request 
  # @return [PaymentFlowResponse]
  describe 'confirm_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.confirm_payment_flow(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.confirm_payment_flow(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for create_payment_flow
  # Create Payment Flow
  # @param payment_flow_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentFlowResponse]
  describe 'create_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.create_payment_flow(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.create_payment_flow(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_payment_flows
  # Get All Payment Flows
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @option opts [String] :customer_id 指定した顧客のデータのみを取得
  # @return [PaymentFlowListResponse]
  describe 'get_all_payment_flows test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_payment_flows()
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_payment_flows(include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_payment_flow
  # Get Payment Flow
  # @param payment_flow_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentFlowResponse]
  describe 'get_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_payment_flow(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_payment_flow(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_payment_flow_refunds
  # Get Payment Flow Refunds
  # Payment Flowに紐づくRefundsをリスト取得する
  # @param payment_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [PaymentRefundListResponse]
  describe 'get_payment_flow_refunds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_payment_flow_refunds(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_payment_flow_refunds(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for update_payment_flow
  # Update Payment Flow
  # @param payment_flow_id 
  # @param payment_flow_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentFlowResponse]
  describe 'update_payment_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.update_payment_flow(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.update_payment_flow(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

end
