=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PaymentIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentIntentsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PaymentIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentIntentsApi' do
    it 'should create an instance of PaymentIntentsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PaymentIntentsApi)
    end
  end

  # unit tests for cancel_payment_intent
  # Cancel Payment Intent
  # @param payment_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentIntentCancelRequest] :payment_intent_cancel_request 
  # @return [PaymentIntentResponse]
  describe 'cancel_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for capture_payment_intent
  # Capture Payment Intent
  # @param payment_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentIntentCaptureRequest] :payment_intent_capture_request 
  # @return [PaymentIntentResponse]
  describe 'capture_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirm_payment_intent
  # Confirm Payment Intent
  # @param payment_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [PaymentIntentConfirmRequest] :payment_intent_confirm_request 
  # @return [PaymentIntentResponse]
  describe 'confirm_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_payment_intent
  # Create Payment Intent
  # @param payment_intent_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'create_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_payment_intent
  # Get All Payment Intent
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [PaymentIntentListResponse]
  describe 'get_all_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for increment_authorization_payment_intent
  # Increment Authorization Payment Intent
  # @param payment_intent_id 
  # @param payment_intent_increment_authorization_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'increment_authorization_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_payment_intent
  # Retrieve Payment Intent
  # @param payment_intent_id 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'retrieve_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_payment_intent
  # Update Payment Intent
  # @param payment_intent_id 
  # @param payment_intent_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PaymentIntentResponse]
  describe 'update_payment_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
