=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PricesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PricesApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PricesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PricesApi' do
    it 'should create an instance of PricesApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PricesApi)
    end
  end

  # unit tests for create_price
  # Create Price
  # @param price_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'create_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.create_price(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.create_price(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_all_prices
  # Get All Prices
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @option opts [Array<String>] :lookup_keys 価格を動的に取得するために使用される検索キー
  # @return [PriceListResponse]
  describe 'get_all_prices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_all_prices()
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_all_prices(include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for get_price
  # Get Price
  # @param price_id 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'get_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.get_price(nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.get_price(nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

  # unit tests for update_price
  # Update Price
  # @param price_id 
  # @param price_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'update_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end

    describe 'with mocked api_client' do
      let(:mock_data) { double('data') }
      let(:mock_status) { 200 }
      let(:mock_headers) { { 'Content-Type' => 'application/json' } }

      before do
        @api_instance.api_client.config.client_side_validation = false
        allow(@api_instance.api_client).to receive(:call_api)
          .and_return([mock_data, mock_status, mock_headers])
      end

      it 'returns data only by default' do
        result = @api_instance.update_price(nil, nil)
        expect(result).to eq(mock_data)
      end

      it 'returns [data, status, headers] with include_http_info: true' do
        result = @api_instance.update_price(nil, nil, include_http_info: true)
        expect(result).to eq([mock_data, mock_status, mock_headers])
      end
    end
  end

end
