=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::PricesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PricesApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::PricesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PricesApi' do
    it 'should create an instance of PricesApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::PricesApi)
    end
  end

  # unit tests for create_price
  # Create Price
  # @param price_create_request 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'create_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_prices
  # Get All Prices
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [PriceListResponse]
  describe 'get_all_prices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_price
  # Get Price
  # @param price_id 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'get_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_price
  # Update Price
  # @param price_id 
  # @param price_update_request 
  # @param [Hash] opts the optional parameters
  # @return [PriceDetailsResponse]
  describe 'update_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
