=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::ProductsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProductsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::ProductsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductsApi' do
    it 'should create an instance of ProductsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::ProductsApi)
    end
  end

  # unit tests for create_product
  # Create Product
  # @param product_create_request 
  # @param [Hash] opts the optional parameters
  # @return [ProductDetailsResponse]
  describe 'create_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_product
  # Delete Product
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @return [ProductDeletedResponse]
  describe 'delete_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_products
  # Get All Products
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [ProductListResponse]
  describe 'get_all_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_product
  # Get Product
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @return [ProductDetailsResponse]
  describe 'get_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_product
  # Update Product
  # @param product_id 
  # @param product_update_request 
  # @param [Hash] opts the optional parameters
  # @return [ProductDetailsResponse]
  describe 'update_product test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
