=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::SetupIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SetupIntentsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::SetupIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetupIntentsApi' do
    it 'should create an instance of SetupIntentsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::SetupIntentsApi)
    end
  end

  # unit tests for cancel_setup_intent
  # Cancel Setup Intent
  # @param setup_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [SetupIntentCancelRequest] :setup_intent_cancel_request 
  # @return [SetupIntentResponse]
  describe 'cancel_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirm_setup_intent
  # Confirm Setup Intent
  # @param setup_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [SetupIntentConfirmRequest] :setup_intent_confirm_request 
  # @return [SetupIntentResponse]
  describe 'confirm_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_setup_intent
  # Create Setup Intent
  # @param [Hash] opts the optional parameters
  # @option opts [SetupIntentCreateRequest] :setup_intent_create_request 
  # @return [SetupIntentResponse]
  describe 'create_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_setup_intent
  # Get All Setup Intent
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [SetupIntentListResponse]
  describe 'get_all_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_setup_intent
  # Retrieve Setup Intent
  # @param setup_intent_id 
  # @param [Hash] opts the optional parameters
  # @return [SetupIntentResponse]
  describe 'retrieve_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_setup_intent
  # Update Setup Intent
  # @param setup_intent_id 
  # @param setup_intent_update_request 
  # @param [Hash] opts the optional parameters
  # @return [SetupIntentResponse]
  describe 'update_setup_intent test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
