=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::SetupFlowsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SetupFlowsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::SetupFlowsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetupFlowsApi' do
    it 'should create an instance of SetupFlowsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::SetupFlowsApi)
    end
  end

  # unit tests for cancel_setup_flow
  # Cancel Setup Flow
  # @param setup_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [SetupFlowCancelRequest] :setup_flow_cancel_request 
  # @return [SetupFlowResponse]
  describe 'cancel_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for confirm_setup_flow
  # Confirm Setup Flow
  # @param setup_flow_id 
  # @param [Hash] opts the optional parameters
  # @option opts [SetupFlowConfirmRequest] :setup_flow_confirm_request 
  # @return [SetupFlowResponse]
  describe 'confirm_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_setup_flow
  # Create Setup Flow
  # @param [Hash] opts the optional parameters
  # @option opts [SetupFlowCreateRequest] :setup_flow_create_request 
  # @return [SetupFlowResponse]
  describe 'create_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_setup_flow
  # Get All Setup Flow
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [String] :starting_after このIDより後のデータを取得
  # @option opts [String] :ending_before このIDより前のデータを取得
  # @return [SetupFlowListResponse]
  describe 'get_all_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_setup_flow
  # Retrieve Setup Flow
  # @param setup_flow_id 
  # @param [Hash] opts the optional parameters
  # @return [SetupFlowResponse]
  describe 'retrieve_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_setup_flow
  # Update Setup Flow
  # @param setup_flow_id 
  # @param setup_flow_update_request 
  # @param [Hash] opts the optional parameters
  # @return [SetupFlowResponse]
  describe 'update_setup_flow test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
