=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::TaxRatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxRatesApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::TaxRatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxRatesApi' do
    it 'should create an instance of TaxRatesApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::TaxRatesApi)
    end
  end

  # unit tests for create_tax_rate
  # Create Tax Rate
  # @param tax_rate_create_request 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateDetailsResponse]
  describe 'create_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_tax_rates
  # Get All Tax Rates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @return [TaxRateListResponse]
  describe 'get_all_tax_rates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tax_rate
  # Get Tax Rate
  # @param tax_rate_id 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateDetailsResponse]
  describe 'get_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tax_rate
  # Update Tax Rate
  # @param tax_rate_id 
  # @param tax_rate_update_request 
  # @param [Hash] opts the optional parameters
  # @return [TaxRateDetailsResponse]
  describe 'update_tax_rate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
