=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PAYJPv2::TermsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TermsApi' do
  before do
    # run before each test
    @api_instance = PAYJPv2::TermsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TermsApi' do
    it 'should create an instance of TermsApi' do
      expect(@api_instance).to be_instance_of(PAYJPv2::TermsApi)
    end
  end

  # unit tests for get_all_term
  # Get All Term
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 取得するデータの最大件数
  # @option opts [Integer] :offset データ取得を行う開始位置
  # @option opts [Time] :since_start_at start_atが指定した日付以降のデータを取得
  # @option opts [Time] :until_start_at start_atが指定した日付以前のデータを取得
  # @return [TermListResponse]
  describe 'get_all_term test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for retrieve_term
  # Retrieve Term
  # @param term_id 
  # @param [Hash] opts the optional parameters
  # @return [TermResponse]
  describe 'retrieve_term test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
