=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::Country
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::Country do
  let(:instance) { PAYJPv2::Country.new }

  describe 'test an instance of Country' do
    it 'should create an instance of Country' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::Country)
    end
  end

end
