=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::DisplayPreferenceRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::DisplayPreferenceRequest do
  let(:instance) { PAYJPv2::DisplayPreferenceRequest.new }

  describe 'test an instance of DisplayPreferenceRequest' do
    it 'should create an instance of DisplayPreferenceRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::DisplayPreferenceRequest)
    end
  end

  describe 'test attribute "preference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["none", "off", "on"])
      # validator.allowable_values.each do |value|
      #   expect { instance.preference = value }.not_to raise_error
      # end
    end
  end

end
