=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::PaymentFlowStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::PaymentFlowStatus do
  let(:instance) { PAYJPv2::PaymentFlowStatus.new }

  describe 'test an instance of PaymentFlowStatus' do
    it 'should create an instance of PaymentFlowStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::PaymentFlowStatus)
    end
  end

end
