=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::PaymentMethodApplePayUpdateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::PaymentMethodApplePayUpdateRequest do
  let(:instance) { PAYJPv2::PaymentMethodApplePayUpdateRequest.new }

  describe 'test an instance of PaymentMethodApplePayUpdateRequest' do
    it 'should create an instance of PaymentMethodApplePayUpdateRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::PaymentMethodApplePayUpdateRequest)
    end
  end

  describe 'test attribute "billing_details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["apple_pay"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
