=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::PaymentMethodOptionsCardRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::PaymentMethodOptionsCardRequest do
  let(:instance) { PAYJPv2::PaymentMethodOptionsCardRequest.new }

  describe 'test an instance of PaymentMethodOptionsCardRequest' do
    it 'should create an instance of PaymentMethodOptionsCardRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::PaymentMethodOptionsCardRequest)
    end
  end

  describe 'test attribute "request_extended_authorization"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["if_available", "never"])
      # validator.allowable_values.each do |value|
      #   expect { instance.request_extended_authorization = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "request_three_d_secure"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["any", "automatic", "challenge"])
      # validator.allowable_values.each do |value|
      #   expect { instance.request_three_d_secure = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "setup_future_usage"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["off_session", "on_session"])
      # validator.allowable_values.each do |value|
      #   expect { instance.setup_future_usage = value }.not_to raise_error
      # end
    end
  end

end
