=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PAYJPv2::RedirectOptionsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PAYJPv2::RedirectOptionsResponse do
  let(:instance) { PAYJPv2::RedirectOptionsResponse.new }

  describe 'test an instance of RedirectOptionsResponse' do
    it 'should create an instance of RedirectOptionsResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PAYJPv2::RedirectOptionsResponse)
    end
  end

  describe 'test attribute "include_client_secret"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
