=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class BalanceResponse
    attr_accessor :object

    # 残高 ID
    attr_accessor :id

    # 本番環境かどうか
    attr_accessor :livemode

    # Balance の状態  | 値 | |:---| | **collecting**: 集計中 | | **transfer**: 入金 | | **claim**: 請求 |
    attr_accessor :state

    # 関連付けられている Statement オブジェクトのリスト
    attr_accessor :statements

    # この Balance の清算が終了していれば true  state=transfer であれば加盟店口座への入金作業完了、state=claim であれば PAY.JP で請求額の振込が確認できたことを表します。
    attr_accessor :closed

    attr_accessor :closed_date

    attr_accessor :due_date

    # 関連付けられている Statement の総額
    attr_accessor :net

    attr_accessor :bank_info

    # 作成日時 (UTC, ISO 8601 形式)
    attr_accessor :created_at

    # 更新時の日時 (UTC, ISO 8601 形式)
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :object => :object,
        :id => :id,
        :livemode => :livemode,
        :state => :state,
        :statements => :statements,
        :closed => :closed,
        :closed_date => :closed_date,
        :due_date => :due_date,
        :net => :net,
        :bank_info => :bank_info,
        :created_at => :created_at,
        :updated_at => :updated_at
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :object => :'String',
        :id => :'String',
        :livemode => :'Boolean',
        :state => :'BalanceState',
        :statements => :'Array<StatementResponse>',
        :closed => :'Boolean',
        :closed_date => :'Time',
        :due_date => :'Time',
        :net => :'Integer',
        :bank_info => :'BankInfoResponse',
        :created_at => :'Time',
        :updated_at => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :closed_date,
        :due_date,
        :bank_info,
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        raise ArgumentError, "The input argument (attributes) must be a hash in `PAYJPv2::BalanceResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          raise ArgumentError, "`#{k}` is not a valid attribute in `PAYJPv2::BalanceResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:object)
        self.object = attributes[:object]
      else
        self.object = 'balance'
      end

      if attributes.key?(:id)
        self.id = attributes[:id]
      else
        self.id = nil
      end

      if attributes.key?(:livemode)
        self.livemode = attributes[:livemode]
      else
        self.livemode = nil
      end

      if attributes.key?(:state)
        self.state = attributes[:state]
      else
        self.state = nil
      end

      if attributes.key?(:statements)
        if (value = attributes[:statements]).is_a?(Array)
          self.statements = value
        end
      else
        self.statements = nil
      end

      if attributes.key?(:closed)
        self.closed = attributes[:closed]
      else
        self.closed = nil
      end

      if attributes.key?(:closed_date)
        self.closed_date = attributes[:closed_date]
      else
        self.closed_date = nil
      end

      if attributes.key?(:due_date)
        self.due_date = attributes[:due_date]
      else
        self.due_date = nil
      end

      if attributes.key?(:net)
        self.net = attributes[:net]
      else
        self.net = nil
      end

      if attributes.key?(:bank_info)
        self.bank_info = attributes[:bank_info]
      else
        self.bank_info = nil
      end

      if attributes.key?(:created_at)
        self.created_at = attributes[:created_at]
      else
        self.created_at = nil
      end

      if attributes.key?(:updated_at)
        self.updated_at = attributes[:updated_at]
      else
        self.updated_at = nil
      end
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('String', ["balance"])
      unless validator.valid?(object)
        raise ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        raise ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] livemode Value to be assigned
    def livemode=(livemode)
      if livemode.nil?
        raise ArgumentError, 'livemode cannot be nil'
      end

      @livemode = livemode
    end

    # Custom attribute writer method with validation
    # @param [Object] state Value to be assigned
    def state=(state)
      if state.nil?
        raise ArgumentError, 'state cannot be nil'
      end

      @state = state
    end

    # Custom attribute writer method with validation
    # @param [Object] statements Value to be assigned
    def statements=(statements)
      if statements.nil?
        raise ArgumentError, 'statements cannot be nil'
      end

      @statements = statements
    end

    # Custom attribute writer method with validation
    # @param [Object] closed Value to be assigned
    def closed=(closed)
      if closed.nil?
        raise ArgumentError, 'closed cannot be nil'
      end

      @closed = closed
    end

    # Custom attribute writer method with validation
    # @param [Object] net Value to be assigned
    def net=(net)
      if net.nil?
        raise ArgumentError, 'net cannot be nil'
      end

      @net = net
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        raise ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        raise ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          object == o.object &&
          id == o.id &&
          livemode == o.livemode &&
          state == o.state &&
          statements == o.statements &&
          closed == o.closed &&
          closed_date == o.closed_date &&
          due_date == o.due_date &&
          net == o.net &&
          bank_info == o.bank_info &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [object, id, livemode, state, statements, closed, closed_date, due_date, net, bank_info, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PAYJPv2.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
