=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module PAYJPv2
  class CheckoutSessionMode
    PAYMENT = "payment".freeze
    SETUP = "setup".freeze

    def self.all_vars
      @all_vars ||= [PAYMENT, SETUP].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CheckoutSessionMode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CheckoutSessionMode"
    end
  end
end
