=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class CheckoutSessionSubmitType
    AUTO = "auto".freeze
    BOOK = "book".freeze
    DONATE = "donate".freeze
    PAY = "pay".freeze

    def self.all_vars
      @all_vars ||= [AUTO, BOOK, DONATE, PAY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CheckoutSessionSubmitType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CheckoutSessionSubmitType"
    end
  end
end
