=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class CheckoutSessionCreateRequest
    # ID
    attr_accessor :client_reference_id

    # 顧客ID
    attr_accessor :customer

    # 顧客オブジェクトを作成する時に使われます。指定されていない場合、顧客にメールアドレスの入力を求めます。すでに顧客のメールアドレスを持っている場合は、このパラメータを使ってあらかじめ情報を入力しておくことが可能です。支払いが完了した後に顧客情報を取得したい場合は、customer属性を使用します。
    attr_accessor :customer_email

    # Checkout Session の確定時に Customer を作成するかどうかを指定します。<br> Customer が作成されない場合でも `customer_details` で Checkout に入力されたメールアドレス、住所、その他の顧客データを取得できます。<br> Customer を作成しない Session は、ダッシュボードでゲスト顧客としてグループ化されます。<br> `payment` および `setup` モードでのみ設定可能です。
    attr_accessor :customer_creation

    # 顧客が購入する商品のリストです。このパラメータを使用して、1回限りまたは定期的な料金を渡します。  `payment` モードの場合、最大100個のラインアイテムを使用できます。 <!-- `subscription` モードの場合、定期的な料金のラインアイテムは最大20個、1回限りの料金のラインアイテムは最大20個です。1回限りの料金のラインアイテムは、最初の請求書にのみ記載されます。 --> 
    attr_accessor :line_items

    # Checkout Session のモード  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 | 
    attr_accessor :mode

    # キーバリューの任意のデータを格納できます。<a href=\"https://docs.pay.jp/v2/metadata\">詳細はメタデータのドキュメントを参照してください。</a>
    attr_accessor :metadata

    # 顧客が支払いを行うか、支払いをキャンセルした後にリダイレクトする URL です。
    attr_accessor :return_url

    # 支払いや設定が完了した際に、PAY.JP が顧客をリダイレクトするURL。成功したCheckout Sessionからの情報をページで使用したい場合は、成功ページのカスタマイズに関するガイドをお読みください。
    attr_accessor :success_url

    # キャンセル時のリダイレクトURL
    attr_accessor :cancel_url

    # Checkout で顧客の請求先住所を収集するかどうかを指定します。デフォルトは `auto` です。  | 指定できる値 | |:---| | **auto**: 請求先住所が必要と判断した場合に入力欄が表示されます。 | | **required**: 常に請求先住所の入力欄が表示されまうs。 | 
    attr_accessor :billing_address_collection

    # 価格の通貨。現在は `jpy` のみサポートしています。
    attr_accessor :currency

    # Checkout Session の有効期限が失効する日時。
    attr_accessor :expires_at

    # Checkout 画面の表示言語を指定します。  | 指定できる値 | |:---| | **ja**: 日本語で表示します。 | 
    attr_accessor :locale

    # `payment` モード指定時に PaymentFlow 作成に使用するパラメーター。
    attr_accessor :payment_flow_data

    # この PaymentFlow の支払い方法の個別設定。
    attr_accessor :payment_method_options

    # この PaymentFlow で使用できる支払い方法の種類（カードなど）のリストです。 指定しない場合、ダッシュボードで利用可能な状態にしている支払い方法を自動的に表示します。
    attr_accessor :payment_method_types

    # `setup` モードの Checkout Session を作成する際、SetupFlow の作成に渡されるパラメーター
    attr_accessor :setup_flow_data

    # Checkout の画面上に表示される送信ボタンなど、ページ上の関連テキストをカスタマイズするために使用されます。<br> `submit_type` は、`payment` モードの Checkout Session でのみ指定できます。未指定時、あるいは `auto` の場合、`pay` が使用されます。  | 指定できる値 | |:---| | **auto**: `pay` が使用されます。 | | **pay**: 「支払う」（デフォルト） | | **book**: 「予約する」 | | **donate**: 「寄付する」 | 
    attr_accessor :submit_type

    # Checkout Session の UI モード。デフォルトは `hosted` です。<br>  | 指定できる値 | |:---| | **hosted**: PAY.JPでホスティングしている画面を使用します。 | 
    attr_accessor :ui_mode

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'client_reference_id' => :'client_reference_id',
        :'customer' => :'customer',
        :'customer_email' => :'customer_email',
        :'customer_creation' => :'customer_creation',
        :'line_items' => :'line_items',
        :'mode' => :'mode',
        :'metadata' => :'metadata',
        :'return_url' => :'return_url',
        :'success_url' => :'success_url',
        :'cancel_url' => :'cancel_url',
        :'billing_address_collection' => :'billing_address_collection',
        :'currency' => :'currency',
        :'expires_at' => :'expires_at',
        :'locale' => :'locale',
        :'payment_flow_data' => :'payment_flow_data',
        :'payment_method_options' => :'payment_method_options',
        :'payment_method_types' => :'payment_method_types',
        :'setup_flow_data' => :'setup_flow_data',
        :'submit_type' => :'submit_type',
        :'ui_mode' => :'ui_mode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'client_reference_id' => :'String',
        :'customer' => :'String',
        :'customer_email' => :'String',
        :'customer_creation' => :'CustomerCreation',
        :'line_items' => :'Array<LineItemRequest>',
        :'mode' => :'CheckoutSessionMode',
        :'metadata' => :'Hash<String, MetadataValue>',
        :'return_url' => :'String',
        :'success_url' => :'String',
        :'cancel_url' => :'String',
        :'billing_address_collection' => :'BillingAddressCollection',
        :'currency' => :'Currency',
        :'expires_at' => :'Time',
        :'locale' => :'Locale',
        :'payment_flow_data' => :'PaymentFlowDataRequest',
        :'payment_method_options' => :'PaymentMethodOptionsRequest',
        :'payment_method_types' => :'Array<PaymentMethodTypes>',
        :'setup_flow_data' => :'SetupFlowDataRequest',
        :'submit_type' => :'CheckoutSessionSubmitType',
        :'ui_mode' => :'CheckoutSessionUIMode'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PAYJPv2::CheckoutSessionCreateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PAYJPv2::CheckoutSessionCreateRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'client_reference_id')
        self.client_reference_id = attributes[:'client_reference_id']
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      end

      if attributes.key?(:'customer_email')
        self.customer_email = attributes[:'customer_email']
      end

      if attributes.key?(:'customer_creation')
        self.customer_creation = attributes[:'customer_creation']
      end

      if attributes.key?(:'line_items')
        if (value = attributes[:'line_items']).is_a?(Array)
          self.line_items = value
        end
      end

      if attributes.key?(:'mode')
        self.mode = attributes[:'mode']
      else
        self.mode = nil
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'return_url')
        self.return_url = attributes[:'return_url']
      end

      if attributes.key?(:'success_url')
        self.success_url = attributes[:'success_url']
      end

      if attributes.key?(:'cancel_url')
        self.cancel_url = attributes[:'cancel_url']
      end

      if attributes.key?(:'billing_address_collection')
        self.billing_address_collection = attributes[:'billing_address_collection']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'expires_at')
        self.expires_at = attributes[:'expires_at']
      end

      if attributes.key?(:'locale')
        self.locale = attributes[:'locale']
      end

      if attributes.key?(:'payment_flow_data')
        self.payment_flow_data = attributes[:'payment_flow_data']
      end

      if attributes.key?(:'payment_method_options')
        self.payment_method_options = attributes[:'payment_method_options']
      end

      if attributes.key?(:'payment_method_types')
        if (value = attributes[:'payment_method_types']).is_a?(Array)
          self.payment_method_types = value
        end
      end

      if attributes.key?(:'setup_flow_data')
        self.setup_flow_data = attributes[:'setup_flow_data']
      end

      if attributes.key?(:'submit_type')
        self.submit_type = attributes[:'submit_type']
      end

      if attributes.key?(:'ui_mode')
        self.ui_mode = attributes[:'ui_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @mode.nil?
        invalid_properties.push('invalid value for "mode", mode cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @mode.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] mode Value to be assigned
    def mode=(mode)
      if mode.nil?
        fail ArgumentError, 'mode cannot be nil'
      end

      @mode = mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          client_reference_id == o.client_reference_id &&
          customer == o.customer &&
          customer_email == o.customer_email &&
          customer_creation == o.customer_creation &&
          line_items == o.line_items &&
          mode == o.mode &&
          metadata == o.metadata &&
          return_url == o.return_url &&
          success_url == o.success_url &&
          cancel_url == o.cancel_url &&
          billing_address_collection == o.billing_address_collection &&
          currency == o.currency &&
          expires_at == o.expires_at &&
          locale == o.locale &&
          payment_flow_data == o.payment_flow_data &&
          payment_method_options == o.payment_method_options &&
          payment_method_types == o.payment_method_types &&
          setup_flow_data == o.setup_flow_data &&
          submit_type == o.submit_type &&
          ui_mode == o.ui_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [client_reference_id, customer, customer_email, customer_creation, line_items, mode, metadata, return_url, success_url, cancel_url, billing_address_collection, currency, expires_at, locale, payment_flow_data, payment_method_options, payment_method_types, setup_flow_data, submit_type, ui_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PAYJPv2.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
