=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class PaymentFlowCreateRequest
    # 支払い予定の金額。50円以上9,999,999円以下である必要があります。
    attr_accessor :amount

    # この PaymentFlow に関連付ける顧客の ID
    attr_accessor :customer_id

    # 支払い方法 ID。customer_id の指定が必須です。Customer が所持する PaymentMethod のみ指定できます。payment_method_id を指定せず、Customer に default_payment_method_id が設定されている場合はそちらが自動でセットされます。
    attr_accessor :payment_method_id

    # この PaymentFlow 固有の支払い方法の設定
    attr_accessor :payment_method_options

    # この PaymentFlow で使用できる支払い方法の種類のリスト。指定しない場合は、PAY.JP は支払い方法の設定から利用可能な支払い方法を動的に表示します。
    attr_accessor :payment_method_types

    # 価格の通貨。現在は `jpy` のみサポートしています。
    attr_accessor :currency

    # 支払いの確定方法を指定します。  | 値 | |:---| | **automatic**: (デフォルト) 顧客が支払いを承認すると、自動的に確定させます。 | | **manual**: 顧客が支払いを承認すると一旦確定を保留し、後で Payment Flow の Capture API を使用して確定します。（すべての支払い方法がこれをサポートしているわけではありません）。 |
    attr_accessor :capture_method

    # 「true」に設定すると、この PaymentFlow を直ちに確定しようと試みます。
    attr_accessor :confirm

    # 顧客が支払いを完了後かキャンセルした後にリダイレクトされる URL。アプリにリダイレクトしたい場合は URI Scheme を指定できます。confirm=true の場合のみ指定できます。
    attr_accessor :return_url

    # オブジェクトにセットする任意の文字列。
    attr_accessor :description

    # キーバリューの任意のデータを格納できます。20件まで登録可能で、空文字列を指定するとそのキーを削除できます。<a href=\"https://docs.pay.jp/v2/guide/developers/metadata\">詳細はメタデータのドキュメントを参照してください。</a>
    attr_accessor :metadata

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :amount => :amount,
        :customer_id => :customer_id,
        :payment_method_id => :payment_method_id,
        :payment_method_options => :payment_method_options,
        :payment_method_types => :payment_method_types,
        :currency => :currency,
        :capture_method => :capture_method,
        :confirm => :confirm,
        :return_url => :return_url,
        :description => :description,
        :metadata => :metadata
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :amount => :'Integer',
        :customer_id => :'String',
        :payment_method_id => :'String',
        :payment_method_options => :'PaymentFlowPaymentMethodOptionsRequest',
        :payment_method_types => :'Array<PaymentMethodTypes>',
        :currency => :'Currency',
        :capture_method => :'CaptureMethod',
        :confirm => :'Boolean',
        :return_url => :'String',
        :description => :'String',
        :metadata => :'Hash<String, MetadataValue>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        raise ArgumentError, "The input argument (attributes) must be a hash in `PAYJPv2::PaymentFlowCreateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          raise ArgumentError, "`#{k}` is not a valid attribute in `PAYJPv2::PaymentFlowCreateRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:amount)
        self.amount = attributes[:amount]
      else
        self.amount = nil
      end

      if attributes.key?(:customer_id)
        self.customer_id = attributes[:customer_id]
      end

      if attributes.key?(:payment_method_id)
        self.payment_method_id = attributes[:payment_method_id]
      end

      if attributes.key?(:payment_method_options)
        self.payment_method_options = attributes[:payment_method_options]
      end

      if attributes.key?(:payment_method_types)
        if (value = attributes[:payment_method_types]).is_a?(Array)
          self.payment_method_types = value
        end
      end

      if attributes.key?(:currency)
        self.currency = attributes[:currency]
      else
        self.currency = nil
      end

      if attributes.key?(:capture_method)
        self.capture_method = attributes[:capture_method]
      end

      if attributes.key?(:confirm)
        self.confirm = attributes[:confirm]
      else
        self.confirm = false
      end

      if attributes.key?(:return_url)
        self.return_url = attributes[:return_url]
      end

      if attributes.key?(:description)
        self.description = attributes[:description]
      end

      if attributes.key?(:metadata)
        if (value = attributes[:metadata]).is_a?(Hash)
          self.metadata = value
        end
      end
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        raise ArgumentError, 'amount cannot be nil'
      end

      if amount > 9999999
        raise ArgumentError, 'invalid value for "amount", must be smaller than or equal to 9999999.'
      end

      if amount < 50
        raise ArgumentError, 'invalid value for "amount", must be greater than or equal to 50.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        raise ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          amount == o.amount &&
          customer_id == o.customer_id &&
          payment_method_id == o.payment_method_id &&
          payment_method_options == o.payment_method_options &&
          payment_method_types == o.payment_method_types &&
          currency == o.currency &&
          capture_method == o.capture_method &&
          confirm == o.confirm &&
          return_url == o.return_url &&
          description == o.description &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [amount, customer_id, payment_method_id, payment_method_options, payment_method_types, currency, capture_method, confirm, return_url, description, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PAYJPv2.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
