=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class PaymentMethodConfigurationDetailsResponse
    attr_accessor :object

    # 支払い方法設定 ID
    attr_accessor :id

    # 本番環境かどうか
    attr_accessor :livemode

    # 設定が有効かどうか
    attr_accessor :active

    attr_accessor :name

    # PayPay の設定
    attr_accessor :paypay

    # カードの設定
    attr_accessor :card

    # Apple Pay の設定
    attr_accessor :apple_pay

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :object => :object,
        :id => :id,
        :livemode => :livemode,
        :active => :active,
        :name => :name,
        :paypay => :paypay,
        :card => :card,
        :apple_pay => :apple_pay
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :object => :'String',
        :id => :'String',
        :livemode => :'Boolean',
        :active => :'Boolean',
        :name => :'String',
        :paypay => :'PaymentMethodConfigurationSettingResponse',
        :card => :'PaymentMethodConfigurationSettingResponse',
        :apple_pay => :'PaymentMethodConfigurationSettingResponse'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :name,
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        raise ArgumentError, "The input argument (attributes) must be a hash in `PAYJPv2::PaymentMethodConfigurationDetailsResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          raise ArgumentError, "`#{k}` is not a valid attribute in `PAYJPv2::PaymentMethodConfigurationDetailsResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:object)
        self.object = attributes[:object]
      else
        self.object = 'payment_method_configuration'
      end

      if attributes.key?(:id)
        self.id = attributes[:id]
      else
        self.id = nil
      end

      if attributes.key?(:livemode)
        self.livemode = attributes[:livemode]
      else
        self.livemode = nil
      end

      if attributes.key?(:active)
        self.active = attributes[:active]
      else
        self.active = nil
      end

      if attributes.key?(:name)
        self.name = attributes[:name]
      else
        self.name = nil
      end

      if attributes.key?(:paypay)
        self.paypay = attributes[:paypay]
      else
        self.paypay = nil
      end

      if attributes.key?(:card)
        self.card = attributes[:card]
      else
        self.card = nil
      end

      if attributes.key?(:apple_pay)
        self.apple_pay = attributes[:apple_pay]
      else
        self.apple_pay = nil
      end
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('String', ["payment_method_configuration"])
      unless validator.valid?(object)
        raise ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        raise ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] livemode Value to be assigned
    def livemode=(livemode)
      if livemode.nil?
        raise ArgumentError, 'livemode cannot be nil'
      end

      @livemode = livemode
    end

    # Custom attribute writer method with validation
    # @param [Object] active Value to be assigned
    def active=(active)
      if active.nil?
        raise ArgumentError, 'active cannot be nil'
      end

      @active = active
    end

    # Custom attribute writer method with validation
    # @param [Object] paypay Value to be assigned
    def paypay=(paypay)
      if paypay.nil?
        raise ArgumentError, 'paypay cannot be nil'
      end

      @paypay = paypay
    end

    # Custom attribute writer method with validation
    # @param [Object] card Value to be assigned
    def card=(card)
      if card.nil?
        raise ArgumentError, 'card cannot be nil'
      end

      @card = card
    end

    # Custom attribute writer method with validation
    # @param [Object] apple_pay Value to be assigned
    def apple_pay=(apple_pay)
      if apple_pay.nil?
        raise ArgumentError, 'apple_pay cannot be nil'
      end

      @apple_pay = apple_pay
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          object == o.object &&
          id == o.id &&
          livemode == o.livemode &&
          active == o.active &&
          name == o.name &&
          paypay == o.paypay &&
          card == o.card &&
          apple_pay == o.apple_pay
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [object, id, livemode, active, name, paypay, card, apple_pay].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PAYJPv2.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
