=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class PaymentFlowCancellationReason
    ABANDONED = "abandoned".freeze
    AUTOMATIC = "automatic".freeze
    DUPLICATE = "duplicate".freeze
    EXPIRED = "expired".freeze
    FAILED_INVOICE = "failed_invoice".freeze
    FRAUDULENT = "fraudulent".freeze
    REQUESTED_BY_CUSTOMER = "requested_by_customer".freeze
    VOID_INVOICE = "void_invoice".freeze

    def self.all_vars
      @all_vars ||= [ABANDONED, AUTOMATIC, DUPLICATE, EXPIRED, FAILED_INVOICE, FRAUDULENT, REQUESTED_BY_CUSTOMER, VOID_INVOICE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PaymentFlowCancellationReason.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PaymentFlowCancellationReason"
    end
  end
end
