=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class PaymentDisputeReason
    RESEARCHING = "researching".freeze
    RESEARCHING_FRAUDULENT = "researching_fraudulent".freeze
    WARNED_FRAUDULENT = "warned_fraudulent".freeze
    CONFIRMED_FRAUDULENT = "confirmed_fraudulent".freeze
    UNRECOGNIZED = "unrecognized".freeze
    FRAUDULENT = "fraudulent".freeze
    PRODUCT_NOT_RECEIVED = "product_not_received".freeze
    ONLINE_FRAUDULENT = "online_fraudulent".freeze
    INCORRECT_ACCOUNT_DETAILS = "incorrect_account_details".freeze
    RECEIVING_CHARGEBACK = "receiving_chargeback".freeze
    DUPLICATE = "duplicate".freeze
    NOT_AUTHORIZED = "not_authorized".freeze
    SUBSCRIPTION_CANCELED = "subscription_canceled".freeze
    CHECK_RETURNED = "check_returned".freeze
    OTHER = "other".freeze

    def self.all_vars
      @all_vars ||= [RESEARCHING, RESEARCHING_FRAUDULENT, WARNED_FRAUDULENT, CONFIRMED_FRAUDULENT, UNRECOGNIZED, FRAUDULENT, PRODUCT_NOT_RECEIVED, ONLINE_FRAUDULENT, INCORRECT_ACCOUNT_DETAILS, RECEIVING_CHARGEBACK, DUPLICATE, NOT_AUTHORIZED, SUBSCRIPTION_CANCELED, CHECK_RETURNED, OTHER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PaymentDisputeReason.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PaymentDisputeReason"
    end
  end
end
