=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module PAYJPv2
  class SetupIntentStatus
    CANCELED = "canceled".freeze
    PROCESSING = "processing".freeze
    REQUIRES_ACTION = "requires_action".freeze
    REQUIRES_CONFIRMATION = "requires_confirmation".freeze
    REQUIRES_PAYMENT_METHOD = "requires_payment_method".freeze
    SUCCEEDED = "succeeded".freeze

    def self.all_vars
      @all_vars ||= [CANCELED, PROCESSING, REQUIRES_ACTION, REQUIRES_CONFIRMATION, REQUIRES_PAYMENT_METHOD, SUCCEEDED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SetupIntentStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SetupIntentStatus"
    end
  end
end
