=begin
#PAY.JP API v2

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class SetupFlowResponse
    attr_accessor :object

    # ID
    attr_accessor :id

    # 本番環境かどうか
    attr_accessor :livemode

    # この SetupFlow のクライアントシークレットです。フロントエンドで公開鍵と合わせて使用し、SetupFlow の取得や支払い方法の登録処理を行います。**この値はこの SetupFlow を利用する顧客以外へ公開しないでください。
    attr_accessor :client_secret

    attr_accessor :customer_id

    attr_accessor :description

    # メタデータ
    attr_accessor :metadata

    attr_accessor :payment_method_id

    attr_accessor :payment_method_options

    # この SetupFlow で使用できる支払い方法の種類のリスト
    attr_accessor :payment_method_types

    # この SetupFlow のステータスです。<a href=\"https://docs.pay.jp/v2/guide/payments/setupflow#setup-flow-%E3%81%AE%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9\" target=\"_blank\">ステータスの詳細についてはこちらをご覧ください。</a>  | 値 | |:---| | **requires_payment_method**: 支払い方法が必要です。 | | **requires_confirmation**: 確認が必要です。 | | **requires_action**: 顧客のアクションが必要です。 | | **processing**: 処理中です。 | | **succeeded**: 成功しました。 | | **canceled**: キャンセルされました。 |
    attr_accessor :status

    attr_accessor :next_action

    attr_accessor :return_url

    attr_accessor :last_setup_error

    attr_accessor :cancellation_reason

    # 作成日時 (UTC, ISO 8601 形式)
    attr_accessor :created_at

    # 更新日時 (UTC, ISO 8601 形式)
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :object => :object,
        :id => :id,
        :livemode => :livemode,
        :client_secret => :client_secret,
        :customer_id => :customer_id,
        :description => :description,
        :metadata => :metadata,
        :payment_method_id => :payment_method_id,
        :payment_method_options => :payment_method_options,
        :payment_method_types => :payment_method_types,
        :status => :status,
        :next_action => :next_action,
        :return_url => :return_url,
        :last_setup_error => :last_setup_error,
        :cancellation_reason => :cancellation_reason,
        :created_at => :created_at,
        :updated_at => :updated_at
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :object => :'String',
        :id => :'String',
        :livemode => :'Boolean',
        :client_secret => :'String',
        :customer_id => :'String',
        :description => :'String',
        :metadata => :'Hash<String, MetadataValue>',
        :payment_method_id => :'String',
        :payment_method_options => :'Hash<String, Object>',
        :payment_method_types => :'Array<PaymentMethodTypes>',
        :status => :'SetupFlowStatus',
        :next_action => :'Hash<String, Object>',
        :return_url => :'String',
        :last_setup_error => :'Hash<String, Object>',
        :cancellation_reason => :'SetupFlowCancellationReason',
        :created_at => :'Time',
        :updated_at => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :customer_id,
        :description,
        :payment_method_id,
        :payment_method_options,
        :next_action,
        :return_url,
        :last_setup_error,
        :cancellation_reason,
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        raise ArgumentError, "The input argument (attributes) must be a hash in `PAYJPv2::SetupFlowResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          raise ArgumentError, "`#{k}` is not a valid attribute in `PAYJPv2::SetupFlowResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:object)
        self.object = attributes[:object]
      else
        self.object = 'setup_flow'
      end

      if attributes.key?(:id)
        self.id = attributes[:id]
      else
        self.id = nil
      end

      if attributes.key?(:livemode)
        self.livemode = attributes[:livemode]
      else
        self.livemode = nil
      end

      if attributes.key?(:client_secret)
        self.client_secret = attributes[:client_secret]
      else
        self.client_secret = nil
      end

      if attributes.key?(:customer_id)
        self.customer_id = attributes[:customer_id]
      else
        self.customer_id = nil
      end

      if attributes.key?(:description)
        self.description = attributes[:description]
      else
        self.description = nil
      end

      if attributes.key?(:metadata)
        if (value = attributes[:metadata]).is_a?(Hash)
          self.metadata = value
        end
      else
        self.metadata = nil
      end

      if attributes.key?(:payment_method_id)
        self.payment_method_id = attributes[:payment_method_id]
      else
        self.payment_method_id = nil
      end

      if attributes.key?(:payment_method_options)
        if (value = attributes[:payment_method_options]).is_a?(Hash)
          self.payment_method_options = value
        end
      else
        self.payment_method_options = nil
      end

      if attributes.key?(:payment_method_types)
        if (value = attributes[:payment_method_types]).is_a?(Array)
          self.payment_method_types = value
        end
      else
        self.payment_method_types = nil
      end

      if attributes.key?(:status)
        self.status = attributes[:status]
      else
        self.status = nil
      end

      if attributes.key?(:next_action)
        if (value = attributes[:next_action]).is_a?(Hash)
          self.next_action = value
        end
      else
        self.next_action = nil
      end

      if attributes.key?(:return_url)
        self.return_url = attributes[:return_url]
      else
        self.return_url = nil
      end

      if attributes.key?(:last_setup_error)
        if (value = attributes[:last_setup_error]).is_a?(Hash)
          self.last_setup_error = value
        end
      else
        self.last_setup_error = nil
      end

      if attributes.key?(:cancellation_reason)
        self.cancellation_reason = attributes[:cancellation_reason]
      else
        self.cancellation_reason = nil
      end

      if attributes.key?(:created_at)
        self.created_at = attributes[:created_at]
      else
        self.created_at = nil
      end

      if attributes.key?(:updated_at)
        self.updated_at = attributes[:updated_at]
      else
        self.updated_at = nil
      end
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] object Object to be assigned
    def object=(object)
      validator = EnumAttributeValidator.new('String', ["setup_flow"])
      unless validator.valid?(object)
        raise ArgumentError, "invalid value for \"object\", must be one of #{validator.allowable_values}."
      end
      @object = object
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        raise ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] livemode Value to be assigned
    def livemode=(livemode)
      if livemode.nil?
        raise ArgumentError, 'livemode cannot be nil'
      end

      @livemode = livemode
    end

    # Custom attribute writer method with validation
    # @param [Object] client_secret Value to be assigned
    def client_secret=(client_secret)
      if client_secret.nil?
        raise ArgumentError, 'client_secret cannot be nil'
      end

      @client_secret = client_secret
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        raise ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_method_types Value to be assigned
    def payment_method_types=(payment_method_types)
      if payment_method_types.nil?
        raise ArgumentError, 'payment_method_types cannot be nil'
      end

      @payment_method_types = payment_method_types
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        raise ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        raise ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        raise ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          object == o.object &&
          id == o.id &&
          livemode == o.livemode &&
          client_secret == o.client_secret &&
          customer_id == o.customer_id &&
          description == o.description &&
          metadata == o.metadata &&
          payment_method_id == o.payment_method_id &&
          payment_method_options == o.payment_method_options &&
          payment_method_types == o.payment_method_types &&
          status == o.status &&
          next_action == o.next_action &&
          return_url == o.return_url &&
          last_setup_error == o.last_setup_error &&
          cancellation_reason == o.cancellation_reason &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [object, id, livemode, client_secret, customer_id, description, metadata, payment_method_id, payment_method_options, payment_method_types, status, next_action, return_url, last_setup_error, cancellation_reason, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PAYJPv2.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
