=begin
#PAY.JP v2 API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module PAYJPv2
  class StatementSubject
     = "売上".freeze
    2 = "決済手数料".freeze
    3 = "プラットフォーム利用料".freeze
    4 = "返金".freeze
    5 = "返金による手数料返還".freeze
    6 = "返金によるプラットフォーム利用料返還".freeze
    7 = "チャージバック".freeze
    8 = "チャージバックによる手数料返還".freeze
    9 = "チャージバックによるプラットフォーム利用料返還".freeze
    10 = "プロプラン利用料".freeze
    11 = "有料プラン料金".freeze
    12 = "残高失効".freeze
    13 = "テナント失効金額の割当て".freeze
    YELL_BANK = "YELL BANKお支払い".freeze
    14 = "早期入金サービス利用料".freeze
    15 = "振込手数料".freeze
    16 = "その他".freeze

    def self.all_vars
      @all_vars ||= [, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, YELL_BANK, 14, 15, 16].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if StatementSubject.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #StatementSubject"
    end
  end
end
